Add sharing is caring
AckeeCZ/ReactiveLocation pull request #6
Opened 2016-10-14 08:46 UTC by olejnjak

2016-10-18 21:17 UTC, janmisar commented
@olejnjak Please make it conflict free 😇

2016-10-19 08:53 UTC, olejnjak commented
@janmisar Fixed

2016-10-19 08:56 UTC, janmisar requested changes

2016-10-19 08:56 UTC, janmisar commented on README.md
> +}.startWithNext { [unowned self] location in
Master branch is Swift 3 & ReactiveSwift so we should provide example in new syntax `startWithValues`.

2016-10-19 08:57 UTC, janmisar commented on README.md
> +}.startWithNext { [unowned self] location in
I should notice before.. sorry 😇

2016-10-19 08:58 UTC, olejnjak commented on README.md
> +}.startWithNext { [unowned self] location in
Good point

2016-10-21 10:22 UTC, olejnjak commented
@janmisar Done

2016-10-24 11:55 UTC, merged